### ISSUE TITLE
Request: more elements in the editor's Advanced (F5) menu

### ISSUE THREAD

**Issue by Espilan** [OpenZoo/ClassicZoo#1]
Board edges are neat and all but I think they're a little lonely in there and could use a bit of company.

Player clones and dummies might be a good start since those would probably get the most mileage, but some other things might be useful too, like bullets (with options for source: player/creature, and direction: N/S/E/W/I?), stars (with option for remaining lifespan, maybe?), or blinkwall lasers.

**Comment by asiekierka** [comment]
Blinkwall lasers will be added in the next ClassicZoo release.

Regarding player clones and dummies: I'm not sure how to expose them in a way which makes most sense to a ZZT newcomer. Thoughts welcome!

Bullets/Stars: Would be nice, yes. I'll try to add them as well.

**Comment by Espilan** [comment]
Considering that both make the game behave in unusual ways depending on how they're used, it may not be a bad idea to offer an explanation for them somewhere in the editor's help, possibly with the F5 menu itself recommending that the help be viewed.

**Comment by asiekierka** [comment]
;Almost implemented as of ClassicZoo 4.12; the remaining lifespan of stars is not yet configurable, however.

**Comment by asiekierka** [comment]
It is now configurable with the low-level tile edit option.
