### ISSUE TITLE
Blinking/Intense color(s) mode like in Kevedit.

### ISSUE THREAD

**Issue by TheRealHamtaro126** [OpenZoo/ClassicZoo#10]
Depending if blinking is high or enabled, I want a "Blink" toggle mode/key where colors are intense or blinking depending on if color blinking is enabled/disabled.

This is seen in KevEdit. where the Blink key is "V" instead of assigning a set of 8 colors to it.

**Comment by asiekierka** [comment]
I'm not a fan of binding it to "V" - but I do agree you should be able to select blinking colors if blinking is enabled.
