### ISSUE TITLE
Unable to use Updated help files 

### ISSUE THREAD

**Issue by viki-t-s** [OpenZoo/ClassicZoo#13]
Hi, 

Firstly, thanks for creating this ZZT port to Modern OS. I am new to ZZT and came across it via Youtube. I am trying to use updated help files from Chronos available in https://museumofzzt.com/file/z/helpfile.zip. While the default ZZT.dat works the updated ones don't work. I cannot figure out what I am overlooking. I followed all the instructions.

**Comment by asiekierka** [comment]
ClassicZoo contains its own updated help files - you don't need to use Chronos's. The ZZT.DAT format has changed to accomodate additional data.
