### ISSUE TITLE
[Returning feature request] Blink on/off mode for intense colors (like in BlinkX) (SDL2)

### ISSUE THREAD

**Issue by TheRealHamtaro126** [OpenZoo/ClassicZoo#14]
Can you still keep the feature for the opttion to turning blinking on/off, like usiing an external TSR (I.E.: BlinkX), or like the blink toggle mode in ZETA., just for SDL2 only?

Thanks.

**Comment by asiekierka** [comment]
It is actually still present, just doesn't show up in the menu due to a bug.

**Comment by asiekierka** [comment]
Fixed in 4.34.
