### ISSUE TITLE
[REQUEST] Add Turbo Pascal 6.0 support

### ISSUE THREAD

**Issue by TheRealHamtaro126** [OpenZoo/ClassicZoo#15]
https://archive.org/details/TP6SrcInst

This Archive.org URL contains Turbo Pascal 6.0 in it's entierty (including binaries, source). Make sure to correctly install it before use.

Thanks again.

**Comment by asiekierka** [comment]
No plans to support non-freely-released versions of Turbo Pascal at the moment; please use Free Pascal if you want more modern features.

**Comment by TheRealHamtaro126** [comment]
Closed, No need for this request thead here... Thanks for your support and help!!!
