### ISSUE TITLE
Inconsistency with ?SPEED cheat and speed selection widget

### ISSUE THREAD

**Issue by DrDos0016** [OpenZoo/ClassicZoo#19]
When using ?SPEED without a number, the default ZZT speed selection widget appears. This widget supports directly jumping to values with the number keys.with 1 being the fastest, 9 being the slowest, and 5 being the default.

When providing a number to set the value without using the widget, rather than use 1-9, 0-8 are used instead meaning "?SPEED 5" and "?SPEED", "5" result in two different speeds being selected.

Worlds like Pepper Bolette that request using a non-default speed use 1-9: https://museumofzzt.com/file/p/bolette(fix-a-dent)/ so I believe making the passed parameter on the cheat prompt work with those values would be the better solution.

**Comment by asiekierka** [comment]
That's a good idea, thank you!
